### ISSUE TITLE
Paths should work either when module is used as a stand-alone pipeline or as a module

### ISSUE THREAD

**Issue by JoseEspinosa** [cbcrg/nf-benchmark#9]
Pipelines are included as modules in `nf-benchmark` but they should keep the autonomy to be run by itself. For instance, when a template is included in a pipeline the `baseDir` when running the pipeline alone is not the same as the one when running the pipeline as a module.

**Comment by pditommaso** [comment]
Exactly each module should be self-contained. What is the problem with that?

**Comment by JoseEspinosa** [comment]
The problem is when for instance a module uses templates. Then when the module it is run as a self alone script it will try to retrieve templates from a different path that when it is run as a module. Also using `baseDir` does not work since this variable takes a different values in this situation

**Comment by JoseEspinosa** [comment]
I solved this issue evaluating the `projectDir.name` and setting the template folder accordingly as you can see here:

https://github.com/JoseEspinosa/regressive_alignment/blob/c43478918874877acce5ff1581a47c876d7cb841/modules/generateAlignment.nf#L4

And the calling templates:

https://github.com/JoseEspinosa/regressive_alignment/blob/c43478918874877acce5ff1581a47c876d7cb841/modules/generateAlignment.nf#L24

@pditommaso do you think is a good approach?

**Comment by pditommaso** [comment]
Maybe is `moduleDir` what you are looking for? 

https://www.nextflow.io/docs/edge/script.html#implicit-variables

**Comment by JoseEspinosa** [comment]
Actually `moduleDir` returns in both cases the same path when accessed from the same script `/my_path/nf-benchmark/modules/regressive_alignment/modules/generateAlignment.nf`:

- running the module from nf-benchmark:

```
my_path/nf-benchmark$ nextflow run main.nf --pipeline regressive_alignment
```
`moduleDir` returns: `/my_path/nf-benchmark/modules/regressive_alignment/./modules/`

- running the module as a stand-alone pipeline:

```
my_path/nf-benchmark/modules/regressive_alignment$ nextflow run main.nf
```

`moduleDir` returns: `/my_path/nf-benchmark/modules/regressive_alignment/./modules/`

**Comment by pditommaso** [comment]
Because you should put the template along with the module, then `moduleDir` tells you the directory where the module is and it can resolve the template relative to it.

**Comment by pditommaso** [comment]
✌️
